### ISSUE TITLE
Bead Frame

### ISSUE THREAD

**Issue by jkayfisch** [mhornbacher/montessori-tools#30]
The colors at the top of the Bead Frame are correct, but the numbers in the units and millions are incorrect.  
The numbers in the white should be              1
                                                           100       10         1

The numbers in the grey are correct.
The numbers in the black should be      1  000  000
                                                            100         10         1

**Comment by mosheduminer** [comment]
@mhornbacher can you comment (since you wrote this one)? I can push a quick fix.

**Comment by mhornbacher** [comment]
I didn't write it but make a PR and I'll fix it

**Comment by mosheduminer** [comment]
@mhornbacher according to git, you are the sole contributor to bead-frame 🤔.

**Comment by mhornbacher** [comment]
Hu, I'll update the readme.

@jkayfisch thank you for your enhancement. It should be live on the site shortly.

**Comment by jkayfisch** [comment]
Thank you!

Will you be adding any other virtual montessori materials?
If you are, I would like to request the multiplication bead board.

Thank you,
Jennifer

**Comment by mosheduminer** [comment]
@jkayfisch we'd be happy to add further materials, for any additional materials, please open a new issue, with a link to a video demonstrating how the material is used (in this case, the multiplication bead board).

Please note that we make no *guarantee* that we will implement a suggestion, nor a timeline. However, we will definitely try to add suggested materials.
